---
networks:
  proxy:
    external: true

services:
  portainer:
    container_name: "portainer"
    image: portainer/portainer-ee:2.42.0@sha256:43a6b52448a0115e13e3cb7009cb3de3a1c0d5ed2e189d5eb2a4dc3c9dfc0dd6
    volumes:
        - data:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9443:9443
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.rule=Host(`portainer.local.weigert.cc`)"
      - "traefik.http.routers.frontend.tls.domains[0].main=local.weigert.cc"
      - "traefik.http.routers.frontend.tls.domains[0].sans=*.local.weigert.cc"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=production"
      - "traefik.http.services.frontend.loadbalancer.server.port=9443"
      - "traefik.http.services.frontend.loadbalancer.server.scheme=https"
      - "traefik.docker.network=proxy"

volumes:
  data:
