---
volumes:
  teamspeak_data:

services:
  teamspeak:
    image: teamspeak:3.13.8@sha256:15acbc64c92f57ef1fd8dd203791fa7f70a14707e60ee494132f26b5ca265c6b
    restart: always
    ports:
      - "10011:10011/tcp"
      - "1337:1337/udp"
      - "30033:30033/tcp"
      - "9987:9987/udp"
    environment:
      TS3SERVER_LICENSE: accept
      TIME_ZONE: Europe/Berlin
    volumes:
      - teamspeak_data:/var/ts3server/
