networks:
  proxy:
    external: true

volumes:
  evcc_data: {}

services:
  evcc:
    command:
      - evcc
    container_name: evcc
    networks: 
      - proxy
    image: evcc/evcc:0.307.2@sha256:9c56c9cdf04d6c036b220adb37bc71e57697e37219d78a9e3290777a566e737e
    ports:
      - 4712:4712/tcp
    volumes:
      #- /mnt/evcc/evcc.yaml:/etc/evcc.yaml
      - evcc_data:/root/.evcc
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.evcc.entryPoints=websecure"
        - "traefik.http.routers.evcc.tls.certResolver=production"
        - "traefik.http.routers.evcc.rule=Host(`evcc.$DOMAIN`)"
        - "traefik.http.services.evcc.loadbalancer.server.port=7070"
        - "traefik.http.routers.evcc.tls.domains[0].main=$DOMAIN"
        - "traefik.http.routers.evcc.tls.domains[0].sans=*.$DOMAIN"
        - "traefik.http.routers.evcc.tls=true"
    restart: unless-stopped