networks:
  proxy:
    external: true

volumes:
  esphome_data: {}

services:
  esphome:
    container_name: esphome
    image: esphome/esphome:2026.6.4@sha256:3df4d482ee77ef65a1b5ae2175779529998d0cfb370f1d95ca008110a015d475
    networks: 
      - proxy
    volumes:
      - esphome_data:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.esphome.entryPoints=websecure"
      - "traefik.http.routers.esphome.tls.certResolver=production"
      - "traefik.http.routers.esphome.rule=Host(`esphome.$DOMAIN`)"
      - "traefik.http.routers.esphome.tls.domains[0].main=$DOMAIN"
      - "traefik.http.routers.esphome.tls.domains[0].sans=*.$DOMAIN"
      - "traefik.http.routers.esphome.tls=true"
    restart: unless-stopped