---
volumes:
  wmbusmeters:

services:
  wmbusmeters:
    image: wmbusmeters/wmbusmeters:latest@sha256:7babaebb455a42c8c4e5eb856e4bbdfa16c3bc82943d4ac3ec0f17d8a2719555
    container_name: wmbusmeters
    privileged: true
    restart: always
    volumes:
      - wmbusmeters:/wmbusmeters_data
      - /etc/localtime:/etc/localtime:ro
      - /dev/:/dev/
    environment:
      - TZ=Europe/Berlin
      - MQTT_PORT=$MQTT_PORT
      - MQTT_PASSWORD=$MQTT_PASSWORD
      - MQTT_USER=$MQTT_USER
      - MQTT_HOST=$MQTT_HOST
