---
networks:
  proxy:
    external: true

volumes:
  homepage:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.14,rw"
      device: ":/mnt/pool-main/docker_volumes/gethomepage"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v2.1.2@sha256:da9dca9ec258c628146bed1445da0853f2b88f0b10bafd97c091de807c363d60
    container_name: homepage
    volumes:
      - homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - proxy
    environment:
      HOMEPAGE_ALLOWED_HOSTS: $HOMEPAGE_ALLOWED_HOSTS
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.entrypoints: "websecure"
      traefik.http.routers.homepage.rule: "Host(`home.$DOMAIN`)"
      traefik.http.routers.homepage.tls.domains[0].main: "$DOMAIN"
      traefik.http.routers.homepage.tls.domains[0].sans: "*.$DOMAIN"
      traefik.http.routers.homepage.tls: "true"
      traefik.http.routers.homepage.tls.certresolver: "production"
      traefik.docker.network: "proxy"
